### ISSUE TITLE
Is this extention depreciated?

### ISSUE THREAD

**Issue by ianTevesAcc** [Joolee/userchrome-toggle#9]
I've tried examples online and have also tried to apply my own implementations to the code, in order to toggle my firefox css to turn off my Tabs Bar and Scrollbars; but I failed in both endeavors. I've seen people implement different css styles of having the css outside of the :root but the extension default code places css inside the root. Either ways I tried both ways but were unsuccessful in both implementations. I don't know what I'm doing wrong, except for the possibility that this extension is already depreciated because it's no longer possible for the current firefox version to inject css to modify the browsers css.

Eitherways the following is the css I tried to implement to be toggleble but failed.
```css
:root[titlepreface*="#TabsToolbar { display: none !important; } #sidebar-header { display: none !important; } #sidebar { min-width: 175px !important; max-width: 700px !important; }"]

:root[titlepreface*="#scrollbar { width: 0; height :0; visibility: hidden !important; }"]
```

This one was the version I kept seeing on other people's code which I implemented as well but still won't work.
```css
:root[titlepreface=""] #TabsToolbar { 
  display: none !important; 
} 
#sidebar-header { 
  display: none !important; 
} 
#sidebar { 
  min-width: 175px !important; 
  max-width: 700px !important; 
}

:root[titlepreface=""] #scrollbar { 
  width: 0; 
  height :0; 
  visibility: hidden !important;
}
```

If I'm doing this wrong then I'm sorry for my ignorance and thank you for the help.

###### *browser without css toggled*
![image](https://github.com/Joolee/userchrome-toggle/assets/105651670/0a8441b1-9359-45b8-92f1-efe79f386a02)
###### *browser with css toggled*
![image](https://github.com/Joolee/userchrome-toggle/assets/105651670/e695e087-064e-4136-bd47-03baced47954)
